spring.application.name=korporis

# Server Configuration
server.port=8080

# Active Profile (change to 'mysql' for production)
spring.profiles.active=h2

# JPA/Hibernate Common Configuration
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
