# Disable dev services
quarkus.devservices.enabled=false

# MySQL Datasource Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/korporis_db}
quarkus.datasource.username=${DB_USERNAME:korporis_username}
quarkus.datasource.password=${DB_PASSWORD:korporis_password}

# Hibernate Configuration
quarkus.hibernate-orm.database.generation=update